.TH "/Users/ericengle/Repos/GitHub/fortran-strings/tests Directory Reference" 3 "Version 1.3.0" "fortran-strings" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/ericengle/Repos/GitHub/fortran-strings/tests Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtest_fortran_strings\&.f90\fP"
.br
.in -1c
