.TH "/Users/ericengle/Repos/GitHub/fortran-strings/README.md" 3 "Version 1.3.0" "fortran-strings" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/ericengle/Repos/GitHub/fortran-strings/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for fortran-strings from the source code\&.
