name: Build and Test on Linux

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sharedlibs: [ON, OFF]
        toolchain:
          - {compiler: gcc, version: 10}
          - {compiler: gcc, version: 11}
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
   
    steps:

    - name: checkout-fortran-strings
      uses: actions/checkout@v3
      with:
        path: fortran-strings
        
    - name: setup-fortran
      uses: awvwgk/setup-fortran@v1
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
        
    - name: build and test
      run: |
        cd fortran-strings
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=${{ matrix.sharedlibs }} ..
        make VERBOSE=1
        make test
