name: Build and Test on Linux

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    #env:
    #strategy:
    #  matrix:
   
    steps:

    - name: checkout-fortran-strings
      uses: actions/checkout@v3
      with:
        path: fortran-strings

    - name: build and test
      run: |
        cd fortran-strings
        mkdir build
        cd build
        cmake ..
        make
        make test
