name: Build and Test on Linux

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - {compiler: gcc, version: 11}
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
   
    steps:

    - name: checkout-fortran-strings
      uses: actions/checkout@v3
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
        path: fortran-strings

    - name: build and test
      run: |
        cd fortran-strings
        mkdir build
        cd build
        cmake ..
        make
        make test
